// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CheckResult 是前端渲染所需的检查结果。HasUpdate 为 false 时其余字段
 * 为零值 —— 当前构建已是最新发布。
 */
export class CheckResult {
    "hasUpdate": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "releaseUrl": string;
    "notes": string;
    "artifactName": string;

    /** Creates a new CheckResult instance. */
    constructor($$source: Partial<CheckResult> = {}) {
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("artifactName" in $$source)) {
            this["artifactName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckResult($$parsedSource as Partial<CheckResult>);
    }
}
