// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService 把 Wails v3 updater（app.Updater）桥接给前端。
 * 应用创建后作为 Service 注册，前端通过生成的绑定驱动 Check /
 * DownloadAndInstall，并订阅 wails:updater:* 事件获取进度。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check 向配置的更新源询问是否有新版本。已是最新时返回 HasUpdate=false
 * 的结果（不视为错误）。
 */
export function Check(): $CancellablePromise<$models.CheckResult | null> {
    return $Call.ByID(3530552157).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CurrentVersion 返回构建时经 -ldflags 注入的版本号。
 */
export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(822912424);
}

/**
 * DownloadAndInstall 下载此前 Check 选中的发布、校验并暂存，等待二进制
 * 替换。应用需重启后新版本才生效 —— 前端监听 wails:updater:update-ready
 * 事件并提示用户。
 */
export function DownloadAndInstall(): $CancellablePromise<void> {
    return $Call.ByID(2213368347);
}

/**
 * Restart 用暂存好的新版本重启应用。Wails updater 会以 helper 模式重新
 * 执行当前进程：等待当前进程退出 → 替换磁盘上的二进制 → 重新拉起，
 * 因此该调用不会返回（替换期间进程即退出）。
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(3977400162);
}

/**
 * State 返回 updater 生命周期阶段（idle/checking/downloading/…）。
 */
export function State(): $CancellablePromise<string> {
    return $Call.ByID(2484664780);
}

// Private type creation functions
const $$createType0 = $models.CheckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
