// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteHandler handles note-related operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Archive archives or unarchives a note
 */
export function Archive(id: number, archive: boolean): $CancellablePromise<void> {
    return $Call.ByID(64154780, id, archive);
}

/**
 * BatchArchive archives multiple notes
 */
export function BatchArchive(ids: number[], archive: boolean): $CancellablePromise<number> {
    return $Call.ByID(2407943248, ids, archive);
}

/**
 * BatchDelete deletes multiple notes
 */
export function BatchDelete(ids: number[]): $CancellablePromise<number> {
    return $Call.ByID(3519843445, ids);
}

/**
 * Create creates a new note
 */
export function Create(title: string, content: string, tags: string[], noteType: string): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(3954156826, title, content, tags, noteType).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Delete soft deletes a note
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2249525673, id);
}

/**
 * GetAll retrieves all notes with optional filters
 */
export function GetAll(limit: number, offset: number, tags: string[], archived: boolean): $CancellablePromise<(models$0.Note | null)[]> {
    return $Call.ByID(2422835985, limit, offset, tags, archived).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAllTags returns all unique tags
 */
export function GetAllTags(): $CancellablePromise<string[]> {
    return $Call.ByID(2256113948).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetByID retrieves a note by ID
 */
export function GetByID(id: number): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(1032416670, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFiltered retrieves notes with advanced filters
 */
export function GetFiltered(limit: number, offset: number, tags: string[], search: string, archived: boolean | null, startTime: string | null, endTime: string | null): $CancellablePromise<(models$0.Note | null)[]> {
    return $Call.ByID(2595843957, limit, offset, tags, search, archived, startTime, endTime).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetStats returns statistics about notes
 */
export function GetStats(): $CancellablePromise<models$0.NoteStats | null> {
    return $Call.ByID(3069911497).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTagsWithCount returns all tags with their usage counts
 */
export function GetTagsWithCount(): $CancellablePromise<(models$0.TagInfo | null)[]> {
    return $Call.ByID(116628650).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * IsFTSEnabled returns whether FTS5 full-text search is enabled
 */
export function IsFTSEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1647030842);
}

/**
 * ResetAllData drops and recreates note-related tables.
 * 用于“清空所有数据，直接删表重建”的场景。
 */
export function ResetAllData(): $CancellablePromise<void> {
    return $Call.ByID(3162351792);
}

/**
 * Search searches notes by query using FTS5
 */
export function Search(query: string, limit: number): $CancellablePromise<models$0.SearchResult | null> {
    return $Call.ByID(1776896046, query, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SearchWithHighlight searches notes and returns highlighted snippets
 */
export function SearchWithHighlight(query: string, limit: number): $CancellablePromise<models$0.SearchResult | null> {
    return $Call.ByID(3892605302, query, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Update updates an existing note
 */
export function Update(id: number, title: string | null, content: string | null, tags: string[] | null): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(237633671, id, title, content, tags).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = models$0.NoteStats.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.TagInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = models$0.SearchResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
