// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * Note represents a note entity
 */
export class Note {
    "id": number;
    "title": string;
    "content": string;
    "tags": string[];

    /**
     * quick or article
     */
    "type": NoteType;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "is_archived": boolean;
    "is_deleted": boolean;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("type" in $$source)) {
            this["type"] = NoteType.$zero;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("is_archived" in $$source)) {
            this["is_archived"] = false;
        }
        if (!("is_deleted" in $$source)) {
            this["is_deleted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new Note($$parsedSource as Partial<Note>);
    }
}

/**
 * NoteStats represents statistics about notes
 */
export class NoteStats {
    "total_notes": number;
    "active_notes": number;
    "archived_notes": number;
    "weekly_count": number;
    "monthly_count": number;
    "all_tags": string[];

    /** Creates a new NoteStats instance. */
    constructor($$source: Partial<NoteStats> = {}) {
        if (!("total_notes" in $$source)) {
            this["total_notes"] = 0;
        }
        if (!("active_notes" in $$source)) {
            this["active_notes"] = 0;
        }
        if (!("archived_notes" in $$source)) {
            this["archived_notes"] = 0;
        }
        if (!("weekly_count" in $$source)) {
            this["weekly_count"] = 0;
        }
        if (!("monthly_count" in $$source)) {
            this["monthly_count"] = 0;
        }
        if (!("all_tags" in $$source)) {
            this["all_tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteStats instance from a string or object.
     */
    static createFrom($$source: any = {}): NoteStats {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("all_tags" in $$parsedSource) {
            $$parsedSource["all_tags"] = $$createField5_0($$parsedSource["all_tags"]);
        }
        return new NoteStats($$parsedSource as Partial<NoteStats>);
    }
}

/**
 * NoteType represents the type of note
 */
export enum NoteType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 灵感小记
     */
    NoteTypeQuick = "quick",

    /**
     * 文章
     */
    NoteTypeArticle = "article",
};

/**
 * SearchResult represents a search result
 */
export class SearchResult {
    "notes": (Note | null)[];
    "total": number;
    "has_more": boolean;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField0_0($$parsedSource["notes"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * TagInfo represents tag information with count
 */
export class TagInfo {
    "name": string;
    "count": number;

    /** Creates a new TagInfo instance. */
    constructor($$source: Partial<TagInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TagInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagInfo($$parsedSource as Partial<TagInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Note.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
