// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// 注：UpdaterHandler 的前端调用在 src/services/updater.ts 用 Call.ByName，不走 bindings。

import * as NoteHandler from "./notehandler.js";
export {
    NoteHandler
};
