// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// 注：UpdaterHandler 为手写新增（用 Call.ByName，见 updaterhandler.ts），非自动生成。

import * as NoteHandler from "./notehandler.js";
import * as UpdaterHandler from "./updaterhandler.js";
export {
    NoteHandler,
    UpdaterHandler
};
