// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteHandler handles note-related operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Archive archives or unarchives a note
 */
export function Archive(id: number, archive: boolean): $CancellablePromise<void> {
    return $Call.ByID(1291897490, id, archive);
}

/**
 * BatchArchive archives multiple notes
 */
export function BatchArchive(ids: number[], archive: boolean): $CancellablePromise<number> {
    return $Call.ByID(2546976298, ids, archive);
}

/**
 * BatchDelete deletes multiple notes
 */
export function BatchDelete(ids: number[]): $CancellablePromise<number> {
    return $Call.ByID(3338650271, ids);
}

/**
 * BatchRestore restores multiple soft-deleted notes.
 */
export function BatchRestore(ids: number[]): $CancellablePromise<number> {
    return $Call.ByID(2638014, ids);
}

/**
 * Create creates a new note
 */
export function Create(title: string, content: string, tags: string[], noteType: string): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(3066879160, title, content, tags, noteType).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Delete soft deletes a note
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(3664437095, id);
}

/**
 * DeleteDraft deletes a draft payload for a note (or global when noteID is nil).
 */
export function DeleteDraft(noteID: number | null): $CancellablePromise<void> {
    return $Call.ByID(1447011490, noteID);
}

/**
 * GetAll retrieves all notes with optional filters
 */
export function GetAll(limit: number, offset: number, tags: string[], archived: boolean): $CancellablePromise<(models$0.Note | null)[]> {
    return $Call.ByID(3783888763, limit, offset, tags, archived).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAllTags returns all unique tags
 */
export function GetAllTags(): $CancellablePromise<string[]> {
    return $Call.ByID(3606397582).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetByID retrieves a note by ID
 */
export function GetByID(id: number): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(1014752848, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDraft gets a draft payload for a note (or global when noteID is nil).
 */
export function GetDraft(noteID: number | null): $CancellablePromise<string> {
    return $Call.ByID(2909151083, noteID);
}

/**
 * GetFiltered retrieves notes with advanced filters
 */
export function GetFiltered(limit: number, offset: number, tags: string[], search: string, archived: boolean | null, startTime: string | null, endTime: string | null): $CancellablePromise<(models$0.Note | null)[]> {
    return $Call.ByID(1850769179, limit, offset, tags, search, archived, startTime, endTime).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSetting gets a backend settings value by key.
 */
export function GetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByID(3170317684, key);
}

/**
 * GetStats returns statistics about notes
 */
export function GetStats(): $CancellablePromise<models$0.NoteStats | null> {
    return $Call.ByID(2214676859).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTagsWithCount returns all tags with their usage counts
 */
export function GetTagsWithCount(): $CancellablePromise<(models$0.TagInfo | null)[]> {
    return $Call.ByID(2399370276).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * IsFTSEnabled returns whether FTS5 full-text search is enabled
 */
export function IsFTSEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1995927172);
}

/**
 * PurgeDeleted physically deletes soft-deleted notes before the given time.
 */
export function PurgeDeleted(beforeTime: string): $CancellablePromise<number> {
    return $Call.ByID(3051525636, beforeTime);
}

/**
 * ResetAllData drops and recreates note-related tables.
 * 用于“清空所有数据，直接删表重建”的场景。
 */
export function ResetAllData(): $CancellablePromise<void> {
    return $Call.ByID(267999646);
}

/**
 * Restore restores a soft-deleted note.
 */
export function Restore(id: number): $CancellablePromise<void> {
    return $Call.ByID(1865612182, id);
}

/**
 * SaveDraft saves a draft payload for a note (or global when noteID is nil).
 */
export function SaveDraft(noteID: number | null, payload: string): $CancellablePromise<void> {
    return $Call.ByID(91129600, noteID, payload);
}

/**
 * Search searches notes by query using FTS5
 */
export function Search(query: string, limit: number): $CancellablePromise<models$0.SearchResult | null> {
    return $Call.ByID(1885328336, query, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SearchWithHighlight searches notes and returns highlighted snippets
 */
export function SearchWithHighlight(query: string, limit: number): $CancellablePromise<models$0.SearchResult | null> {
    return $Call.ByID(1062822664, query, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SetSetting sets a backend settings key/value pair.
 */
export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3048781216, key, value);
}

/**
 * Update updates an existing note
 */
export function Update(id: number, title: string | null, content: string | null, tags: string[] | null): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(2834942573, id, title, content, tags).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateWithVersion updates an existing note with optimistic version check.
 */
export function UpdateWithVersion(id: number, title: string | null, content: string | null, tags: string[] | null, expectedVersion: number | null): $CancellablePromise<models$0.Note | null> {
    return $Call.ByID(2703469371, id, title, content, tags, expectedVersion).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = models$0.NoteStats.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.TagInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = models$0.SearchResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
